In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from collections import Counter

In [2]:
dataset = pd.read_csv('../Files/ml.csv', sep=';') # Zamienić separator na średnik
dataset.head()

,lp,data,n1,n2,n3,n4,n5,n6,n7,n8,...,n11,n12,n13,n14,n15,n16,n17,n18,n19,n20
0,14651.0,15.06.2023,1,10,13,15,16,20,23,26,...,36,38,45,50,51,56,63,71,78,80
1,14632.0,16.06.2023,7,11,12,13,18,30,32,36,...,41,47,54,58,68,69,70,75,76,79
2,14633.0,06.06.2023,1,2,3,5,6,12,13,14,...,30,35,36,39,51,54,68,70,74,79
3,14634.0,07.06.2023,14,26,27,29,36,37,42,43,...,47,54,57,58,63,65,70,72,73,76
4,14635.0,07.06.2023,1,6,11,16,20,21,25,27,...,43,56,58,62,65,66,67,72,77,80

In [3]:
# Utwórz listę z danymi kolumn n1, n2, n3, n4, n5 i n6
dane = dataset[['n1', 'n2', 'n3', 'n4', 'n5', 'n6', 'n7', 'n8', 'n9', 'n10', 'n11', 'n12', 'n13', 'n14', 'n15', 'n16', 'n17', 'n18', 'n19', 'n20']].values.tolist()

In [4]:
wyniki = []
for sublist in dane:
    wyniki.extend(sublist)

In [5]:
liczby_wystapienia = dict(Counter(wyniki))

# Wyliczenia

In [6]:
# Definiowanie przedziałów
przedzialy = {
    '1-10': 0,
    '11-20': 0,
    '21-30': 0,
    '31-40': 0,
    '41-50': 0,
    '51-60': 0,
    '61-70': 0,
    '71-80': 0

}

# Przypisywanie wartości wystąpień do odpowiednich przedziałów
for liczba, wystapienia in liczby_wystapienia.items():
    if 1 <= liczba <= 10:
        przedzialy['1-10'] += wystapienia
    elif 11 <= liczba <= 20:
        przedzialy['11-20'] += wystapienia
    elif 21 <= liczba <= 30:
        przedzialy['21-30'] += wystapienia
    elif 31 <= liczba <= 40:
        przedzialy['31-40'] += wystapienia
    elif 41 <= liczba <= 50:
        przedzialy['41-50'] += wystapienia
    elif 51 <= liczba <= 60:
        przedzialy['51-60'] += wystapienia
    elif 61 <= liczba <= 70:
        przedzialy['61-70'] += wystapienia
    elif 71 <= liczba <= 80:
        przedzialy['71-80'] += wystapienia

# Wypisz wyniki
for przedzial, liczba_wystapien in przedzialy.items():
    print(f"Przedział {przedzial}: {liczba_wystapien} wystąpień.")

Przedział 1-10: 43 wystąpień.
Przedział 11-20: 52 wystąpień.
Przedział 21-30: 49 wystąpień.
Przedział 31-40: 49 wystąpień.
Przedział 41-50: 52 wystąpień.
Przedział 51-60: 51 wystąpień.
Przedział 61-70: 43 wystąpień.
Przedział 71-80: 61 wystąpień.

In [7]:
# Sortowanie przedziałów malejąco według liczby wystąpień
posortowane_przedzialy = sorted(przedzialy.items(), key=lambda x: x[1], reverse=True)

# Wyświetlanie 2 wartości, które wystąpiły najczęściej w każdym przedziale
for przedzial, liczba_wystapien in posortowane_przedzialy:
    print(f"Przedział {przedzial}: {liczba_wystapien} wystąpień.")
    
# Tworzenie słownika wartości wystąpień dla danego przedziału
    wartosci_wystapien = {}
    for sublist in dane:
        for liczba in sublist:
            if liczba >= int(przedzial.split('-')[0]) and liczba <= int(przedzial.split('-')[1]):
                if liczba in wartosci_wystapien:
                    wartosci_wystapien[liczba] += 1
                else:
                    wartosci_wystapien[liczba] = 1
    
# Sortowanie wartości wystąpień malejąco
    posortowane_wartosci = sorted(wartosci_wystapien.items(), key=lambda x: x[1], reverse=True)
    
# Wyświetlanie dwóch wartości wystąpień najczęściej występujących
    for wartosc, wystapienia in posortowane_wartosci[:2]:
        print(f" - Wartość: {wartosc}, wystąpienia: {wystapienia}")

Przedział 71-80: 61 wystąpień.
 - Wartość: 79, wystąpienia: 9
 - Wartość: 75, wystąpienia: 8
Przedział 11-20: 52 wystąpień.
 - Wartość: 16, wystąpienia: 8
 - Wartość: 15, wystąpienia: 7
Przedział 41-50: 52 wystąpień.
 - Wartość: 45, wystąpienia: 8
 - Wartość: 42, wystąpienia: 8
Przedział 51-60: 51 wystąpień.
 - Wartość: 55, wystąpienia: 10
 - Wartość: 56, wystąpienia: 8
Przedział 21-30: 49 wystąpień.
 - Wartość: 21, wystąpienia: 8
 - Wartość: 22, wystąpienia: 7
Przedział 31-40: 49 wystąpień.
 - Wartość: 36, wystąpienia: 9
 - Wartość: 31, wystąpienia: 6
Przedział 1-10: 43 wystąpień.
 - Wartość: 1, wystąpienia: 7
 - Wartość: 6, wystąpienia: 7
Przedział 61-70: 43 wystąpień.
 - Wartość: 62, wystąpienia: 8
 - Wartość: 63, wystąpienia: 6